# Generated by Django 5.1.3 on 2024-11-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_remove_comment_user_comment_author_comment_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='video',
            name='created_at',
        ),
    ]
