# Generated by Django 5.1.3 on 2024-11-19 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_remove_comment_created_at_remove_video_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='videos.youtubevideo'),
        ),
        migrations.RemoveField(
            model_name='youtubevideo',
            name='pub_date',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
